import App from "./application";
import Router from "./router";
import { IApp } from "./types";
import { BadRequestError, UnprocessableEntityError, BaskomError, ForbiddenError, UnauthorizedError, NotFoundError, MethodNotAllowedError, InternalServerError } from './error';
import {  wrap } from "./utils";

const baskom = ({ useParseQueryString, useParseUrl, useDebugError, useBodyLimit, useDefaultBody }: IApp = {}) => new App({ useParseQueryString, useParseUrl, useDebugError, useBodyLimit, useDefaultBody });
baskom.router = () => new Router();
baskom.Router = Router;
baskom.wrap = (fn: Function) => wrap(fn);
baskom.BaskomError = BaskomError;
baskom.BadRequestError = BadRequestError;
baskom.UnauthorizedError = UnauthorizedError;
baskom.ForbiddenError = ForbiddenError;
baskom.NotFoundError = NotFoundError;
baskom.MethodNotAllowedError = MethodNotAllowedError;
baskom.UnprocessableEntityError = UnprocessableEntityError;
baskom.InternalServerError = InternalServerError;
export = baskom;
// export default baskom;